### ISSUE TITLE
No module named refine

### ISSUE THREAD

**Issue by adriancobb** [opencultureconsulting/openrefine-batch#1]
I got an error saying "ImportError: No module named refine" as follow: 

```
$ ./openrefine-batch.sh -a input/ -b config/ -c OUTPUT/
Download OpenRefine client...
Install OpenRefine client in subdirectory openrefine-client...
Total bytes read: 3082240 (3.0MiB, 87MiB/s)

Input directory:         /home/hadoop/OpenRefine/openrefine-batch/input
Input files:             universityData2.csv
Input format:            
Input options:           
Config directory:        /home/hadoop/OpenRefine/openrefine-batch/config
Transformation rules:    university.json
Cross directory:         /dev/null
Cross projects:          
OpenRefine heap space:   2048M
OpenRefine port:         3333
OpenRefine workspace:    /home/hadoop/OpenRefine/openrefine-batch/OUTPUT
Export TSV to workspace: true
restart after file:      true
restart after transform: true

=== 1. Launch OpenRefine ===

starting time: Mon Jul 31 05:20:43 PDT 2017


=== 2. Import all files ===

starting time: Mon Jul 31 05:20:46 PDT 2017

import universityData2.csv...
Traceback (most recent call last):
  File "openrefine-client/refine.py", line 27, in <module>
    from google.refine import refine
ImportError: No module named refine
 STARTED     ELAPSED %MEM %CPU   RSS
05:20:42       00:04  0.1  0.0  2004

save project and restart OpenRefine server...

./openrefine-batch.sh: line 223:  6791 Terminated              openrefine/refine -p ${port} -d "${outputdir}" -m ${ram}

=== 3. Prepare transform & export ===

starting time: Mon Jul 31 05:20:47 PDT 2017

get project ids...
Traceback (most recent call last):
  File "openrefine-client/refine.py", line 27, in <module>
    from google.refine import refine
ImportError: No module named refine

output (number of lines / size in bytes):
wc: /home/hadoop/OpenRefine/openrefine-batch/OUTPUT/*.tsv: No such file or directory

cleanup...
./openrefine-batch.sh: line 358:  6832 Terminated              openrefine/refine -p ${port} -d "${outputdir}" -m ${ram}

=== Statistics ===

starting time and run time of each step:
                      Start process Mon Jul 31 05:20:43 PDT 2017 (00:00:00)
                  Launch OpenRefine Mon Jul 31 05:20:43 PDT 2017 (00:00:03)
                   Import all files Mon Jul 31 05:20:46 PDT 2017 (00:00:01)
         Prepare transform & export Mon Jul 31 05:20:47 PDT 2017 (00:00:00)
                        End process Mon Jul 31 05:20:47 PDT 2017 (00:00:00)

total run time: 00:00:04 (hh:mm:ss)
highest memory load: 1 MB
```

Not sure why is that? Could you please help? Thanks.

**Comment by felixlohmeier** [comment]
The shell script openrefine-batch.sh executes the file openrefine-client/refine.py which imports another python module located in subdirectory openrefine-client/google/refine/refine.py. The error message "ImportError: No module named refine" indicates that your system/python environment does not recognize the package structure.

Please try executing the python client directly with a fixed search path for module files:
```
cd /home/hadoop/OpenRefine/openrefine-batch/
PYTHONPATH="/home/hadoop/OpenRefine/openrefine-batch/openrefine-client" openrefine-client/refine.py
```

If this works then you can replace all mentions of refine.py in the shell script openrefine-batch.sh:
```
sed -i 's/openrefine-client\/refine.py/PYTHONPATH="\/home\/hadoop\/OpenRefine\/openrefine-batch\/openrefine-client" openrefine-client\/refine.py/' openrefine-batch.sh
```

**Comment by felixlohmeier** [comment]
I build a one-file-executable for the client to get rid of the python dependencies. Please try the new release (delete old files and directories first):
```
wget https://github.com/felixlohmeier/openrefine-batch/raw/master/openrefine-batch.sh && chmod +x openrefine-batch.sh
```

**Comment by adriancobb** [comment]
Thanks! That would be great.
